name: "Debug APK Publisher"
branding:
  icon: "package"
  color: "red"
description: "Build & Publish Debug APK on Github"
author: "ShaunLWM"
inputs:
  GITHUB_TOKEN:
    required: true
    description: "Github secret token to allow automated publishing of APK to release."
  REPO_BRANCH:
    required: false
    description: "Github repository branch name."
runs:
  using: "docker"
  image: "Dockerfile"
name: Build & Publish Debug APK

on:
 push:
  branches:
   - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build Debug APK
      run: ./gradlew assembleProdDebuggable
    - name: Releasing using Hub
      uses: melsu90/action-release-debugapk@master
      env:
       GITHUB_TOKEN: ${{ secrets.TOKEN }}
       APP_FOLDER: app
       RELEASE_TITLE: New Build
